# Some of the content has been relocated to the locale folder within the configuration file.

# Locale, Current support:
# en(English), zh_tw(繁體中文_臺灣)
# Help us to translate to other languages at Crowdin!
# https://crowdin.com/project/catchball
Locale: en

# Whether the plugin checks for updates and posts the message on the console
Update-Check: true

# Whether the chickens will drop the "GoldEgg" (true/false)
ChickenDropGoldEgg: true

# Chance of chicken to drop GoldEgg
ChickenDropGoldEggChance: 50%

# Captured sound effects, No sound to type (false)
# Sound Support: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
CatchSuccessSound: ENTITY_ARROW_HIT_PLAYER

# "AllowCatchableTamedOwnerIsNull" likely refers to the option of permitting players to capture tamed entities with a null owner, potentially affecting the entity capture mechanics by allowing acquisition of ownerless tamed entities.
AllowCatchableTamedOwnerIsNull: true

# Show particles if player catches entity.
# This is an unstable feature, please report all bugs to our Discord or GitHub issues.
ShowParticles: false

# What particle do you want?
# Particle Support: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
CustomParticles: CAMPFIRE_COSY_SMOKE

# The probability (0-1) of a failed attempt to catch an entity. Set this value to 0 to disable this feature.
# Setting it to 1 would mean every attempt to catch an entity would fail.
# This is an unstable feature, please report all bugs to our Discord or GitHub issues.
catchFailRate: 0.0

# CatchBall on CraftRecipe
Recipe:
    # Whether to turn it on or off
    enabled: true
    # Recipe key
    key:
        # GOLDEGG is the plugin provided custom item
        # Item Support: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/material/package-summary.html
        G: GOLDEGG
    # Recipe
    shape:
        - "GGG"
        - "GGG"
        - "GGG"

# Disable if you don't want CatchBall check Residence flag
UseRes: true
# Catcher must have this permission flag to capture entity (depends on Plugin Residence)
ResidenceFlag:
    - animalkilling

# Disable if you don't want CatchBall check GriefPrevention flag
UseGF: true
# Catcher must have this permission flag to capture entity (depends on Plugin GriefPrevention)
GriefPreventionFlag:
    - Access

# Disable if you don't want CatchBall check Lands flag
UseLands: true

# Disable if you don't want CatchBall to use PlaceholderAPI in messages
UsePAPI: true

# Disable if you don't want CatchBall check MythicMobs mobs
UseMM: true

CatchableEntity:
    - SHEEP
